from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional, Tuple

import numpy as np


@dataclass
class Task:
    """Computation task T_k = (D_k, C_k) generated by a vehicle."""

    task_id: int
    vehicle_id: int
    created_at: float
    data_size_mbits: float
    compute_demand_gcycles: float
    source_position: np.ndarray
    deadline_s: float = 5.0
    assigned_drone_id: Optional[int] = None
    completed: bool = False
    failed: bool = False
    completed_at: Optional[float] = None


@dataclass
class Drone:
    drone_id: int
    position: np.ndarray
    battery_j: float
    max_speed_mps: float
    velocity: np.ndarray = field(default_factory=lambda: np.zeros(2, dtype=np.float32))
    total_energy_j: float = 0.0
    total_distance_m: float = 0.0

    def apply_action(self, action: np.ndarray) -> np.ndarray:
        action = np.asarray(action, dtype=np.float32)
        speed = float(np.linalg.norm(action))
        if speed > self.max_speed_mps:
            action = action / (speed + 1e-8) * self.max_speed_mps
        self.velocity = action
        return action

    def state_vector(self, area_size: Tuple[float, float], initial_battery_j: float) -> np.ndarray:
        return np.array(
            [
                self.position[0] / area_size[0],
                self.position[1] / area_size[1],
                self.position[2] / max(self.position[2], 1.0),
                self.velocity[0] / self.max_speed_mps,
                self.velocity[1] / self.max_speed_mps,
                self.battery_j / initial_battery_j,
            ],
            dtype=np.float32,
        )


@dataclass
class Vehicle:
    vehicle_id: int
    position: np.ndarray
    route: List[np.ndarray]
    speed_mps: float
    route_index: int = 0

    def state_vector(self, area_size: Tuple[float, float]) -> np.ndarray:
        return np.array(
            [self.position[0] / area_size[0], self.position[1] / area_size[1]],
            dtype=np.float32,
        )
